=== Git-Host/jawyl/system/schemas/locale.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xsd:element name="locale">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="syslocale" type="xsd:string" minOccurs="0" />
			<xsd:element name="symbols">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="decseparator" type="xsd:string" />
						<xsd:element name="digseparator" type="xsd:string" />
						<xsd:element name="negativesign" type="xsd:string" />
						<xsd:element name="intercurrency" type="xsd:string" />
						<xsd:element name="localcurrency" type="xsd:string" />
						<xsd:element name="timeseparator" type="xsd:string" />
						<xsd:element name="dateseparator" type="xsd:string" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="formats">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="number" type="xsd:string" />
						<xsd:element name="currency" type="xsd:string" />
						<xsd:element name="date" type="xsd:string" />
						<xsd:element name="time" type="xsd:string" />
						<xsd:element name="datetime" type="xsd:string" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="months">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="month" minOccurs="12" maxOccurs="12">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="xsd:string">
										<xsd:attribute name="order" type="xsd:int" use="required" />
										<xsd:attribute name="shortname" type="xsd:string" use="required" />
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="weekdays">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="weekday" minOccurs="7" maxOccurs="7">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="xsd:string">
										<xsd:attribute name="order" type="xsd:byte" use="required" />
										<xsd:attribute name="shortname" type="xsd:string" use="required" />
										<xsd:attribute name="minname" type="xsd:string" use="required" />
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
					<xsd:attribute name="firstday" type="xsd:int" use="optional" />
				</xsd:complexType>			
			</xsd:element>			
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
</xsd:schema>

=== Git-Host/jawyl/system/locales/RU_ru.xml
<?xml version="1.0" encoding="UTF-8"?>
<locale xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/locale.xsd">
	<description>Русская локализация</description>
	<syslocale>rus_rus</syslocale>
	<symbols>
		<decseparator>,</decseparator>
		<digseparator><![CDATA[ ]]></digseparator>
		<negativesign>-</negativesign>
		<intercurrency>RUR</intercurrency>
		<localcurrency>р.</localcurrency>
		<timeseparator>:</timeseparator>
		<dateseparator>.</dateseparator>
	</symbols>
	<formats>
		<number>#{dig}##0{dec}##</number>
		<currency>#{dig}##0{dec}00 {lc}</currency>
		<date>d{ds}m{ds}y</date>
		<time>H{ts}i{ts}s</time>
		<datetime>d{ds}m{ds}y H{ts}i{ts}s</datetime>
	</formats>
	<months>
		<month order="1" shortname="Янв">Январь</month>
		<month order="2" shortname="Фев">Февраль</month>
		<month order="3" shortname="Мар">Март</month>
		<month order="4" shortname="Апр">Апрель</month>
		<month order="5" shortname="Май">Май</month>
		<month order="6" shortname="Июн">Июнь</month>
		<month order="7" shortname="Июл">Июль</month>
		<month order="8" shortname="Авг">Август</month>
		<month order="9" shortname="Сен">Сентябрь</month>
		<month order="10" shortname="Окт">Октябрь</month>
		<month order="11" shortname="Ноя">Ноябрь</month>
		<month order="12" shortname="Дек">Декабрь</month>
	</months>
	<weekdays firstday="1">
		<weekday order="1" shortname="Вск" minname="Вс">Воскресенье</weekday>
		<weekday order="2" shortname="Пнд" minname="Пн">Понедельник</weekday>
		<weekday order="3" shortname="Втр" minname="Вт">Вторник</weekday>
		<weekday order="4" shortname="Срд" minname="Ср">Среда</weekday>
		<weekday order="5" shortname="Чтв" minname="Чт">Четверг</weekday>
		<weekday order="6" shortname="Птн" minname="Пт">Пятница</weekday>
		<weekday order="7" shortname="Суб" minname="Сб">Суббота</weekday>
	</weekdays>	
</locale>

=== Git-Host/jawyl/system/locales/us_EN.xml
<?xml version="1.0" encoding="UTF-8"?>
<locale xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/locale.xsd">
	<description>US locale</description>
	<syslocale>eng_usa</syslocale>
	<symbols>
		<decseparator>.</decseparator>
		<digseparator>,</digseparator>
		<negativesign>-</negativesign>
		<intercurrency>USD</intercurrency>
		<localcurrency>$</localcurrency>
		<timeseparator>:</timeseparator>
		<dateseparator>/</dateseparator>
	</symbols>
	<formats>
		<number>#{dig}##0{dec}####</number>
		<currency>#{dig}##0{dec}00{lc}</currency>
		<date>m{ds}d{ds}Y</date>
		<time>h{ts}i{ts}s</time>
		<datetime>m{ds}d{ds}Y h{ts}i{ts}s A</datetime>
	</formats>
	<months>
		<month order="1" shortname="Jan">January</month>
		<month order="2" shortname="Feb">February</month>
		<month order="3" shortname="Mar">March</month>
		<month order="4" shortname="Apr">April</month>
		<month order="5" shortname="May">May</month>
		<month order="6" shortname="Jun">June</month>
		<month order="7" shortname="Jul">July</month>
		<month order="8" shortname="Aug">August</month>
		<month order="9" shortname="Sep">September</month>
		<month order="10" shortname="Oct">October</month>
		<month order="11" shortname="Nov">November</month>
		<month order="12" shortname="Dec">December</month>
	</months>
	<weekdays firstday="0">
		<weekday order="1" shortname="Sun" minname="Su">Sunday</weekday>
		<weekday order="2" shortname="Mon" minname="Mo">Monday</weekday>
		<weekday order="3" shortname="Thu" minname="Tu">Thuesday</weekday>
		<weekday order="4" shortname="Wed" minname="We">Wednesday</weekday>
		<weekday order="5" shortname="Thu" minname="Th">Thursday</weekday>
		<weekday order="6" shortname="Fri" minname="Fr">Friday</weekday>
		<weekday order="7" shortname="Sat" minname="Sa">Saturday</weekday>
	</weekdays>	
</locale>
